spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:dockerhost}:${POSTGRES_PORT:9712}/${POSTGRES_DATABASE:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driverClassName: org.postgresql.Driver
    platform: postgres
  liquibase:
    change-log: classpath:db/changelog/migrations.xml
    enabled: ${COLD_BOOT:true}