spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:dockerhost}:${POSTGRES_PORT:9712}/${POSTGRES_DATABASE:springtest}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driverClassName: org.postgresql.Driver
    platform: postgres
  liquibase:
    change-log: classpath:db/changelog/migrations.xml
    enabled: ${COLD_BOOT:false}
---
spring:
  profiles: rest
  main:
    web-application-type: servlet
---
spring:
  profiles: task
  liquibase:
    enabled: false